import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { headers } from "next/headers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const activePath = headers().get("x-invoke-path")

  if (activePath === "/login") {
    return (
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    )
  } else {
    return (
      <html lang="en">
        <body className={inter.className}>
          <header>Header</header>
          {children}
          <footer>Footer</footer>
        </body>
      </html>
    )
  }
}
